[toolchain]
anchor_version = "0.30.0"
solana_version = "1.18.12"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pvp_battle = "PVPjBGSfMFEfQmdaWUemUjcTnLz4KcUaZjRiPsJ8JKh"
global_settings = "GSoG5Tz9LVWzLrEvLgo9q4JqJYWk2Prx9VjzrAeTzYFk"

[provider]
cluster = "localnet"
# cluster = "devnet"
# cluster = "https://mainnet.helius-rpc.com/?api-key=50f0af07-1a64-4b06-bfdd-af3811ff9e2a"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -r tsconfig-paths/register tests/*.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -r tsconfig-paths/register tests/raydium/test_cpmm.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112" # WSOL

[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB" # USDT

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # USDC
